In [1]:
#encoding categorical data
#data is of 2 types:

# 1) numerical : like age, weight, height, price etc
# 2) categorical: sex, class, degree, city, country etc

In [3]:
#categorical data is of 2 types:

# 1) Nominal: categorical data which has no order for ex: states, hr, up, mp, kerela.. 
#         you cant say up comes first & mp comes last, it has no order
        
# 2) Ordinal: categorical data which order like grades: first, secod, third etc 
#         or political leader: MLA, CM, PM etc which has order 

In [4]:
#how to encode categorical data?
#bcoz ml algo expect numbers only & not strings

In [6]:
#for categorical data:

#if X (input col) has ordinal categorical data then use ordinal encodeing
#if y (output col) has categorical data then use label encoding

In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('customer.csv')

In [9]:
df.sample(5)

age  gender review education purchased
43   27    Male   Poor        PG        No
12   51    Male   Poor    School        No
22   18  Female   Poor        PG       Yes
15   75    Male   Poor        UG        No
11   74    Male   Good        UG       Yes

In [11]:
#check what kind of data you have in each columns

#age is numerical
#gender is categorical: nominal
#review is categorical: ordinal
#education is categorical: ordinal
#purchased is categorical: nominal but since output is categorical so apply label encoding

In [12]:
df = df.iloc[:,2:]

In [13]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [18]:
X_train

review education
2      Good        PG
39     Poor        PG
20  Average    School
7      Poor    School
28     Poor    School
41     Good        PG
11     Good        UG
46     Poor        PG
8   Average        UG
38     Good    School
9      Good        UG
23     Good    School
22     Poor        PG
19     Poor        PG
13  Average    School
16     Poor        UG
17     Poor        UG
31     Poor    School
25     Good    School
3      Good        PG
29  Average        UG
1      Poor        UG
40     Good    School
5   Average    School
36     Good        UG
43     Poor        PG
32  Average        UG
34  Average    School
49     Good        UG
44  Average        UG
30  Average        UG
24  Average        PG
10     Good        UG
42     Good        PG
21  Average        PG
48     Good        UG
27     Poor        PG
6      Good    School
15     Poor        UG
26     Poor        PG

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [24]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

#if i dont pass this hirarchy info then it will decided randomly
# may be UG gets last no. & School gets highest no. which is incorreect

In [26]:
#fit on train & transform on train & test both

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [27]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [28]:
X_train

array([[2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.]])

In [29]:
X_test

array([[0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.]])

In [30]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [31]:
#label concoding output column

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le = LabelEncoder()

In [34]:
le.fit(y_train)

LabelEncoder()

In [35]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [36]:
#fit on train data & transform train & test both

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [37]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0])

In [38]:
y_test

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 0])